/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Backward-compatible API that accepts a JavaScript number and rounds to the nearest cent.
 * Prefer `rmbToRmbFromString` for deterministic financial formatting.
 */
export function rmbToRmb(n: number): string

/**
 * Converts an amount represented in cents into uppercase RMB text.
 * The cents value is accepted as a string for large integer amounts.
 */
export function rmbToRmbFromCents(cents: string): string

/**
 * Parses a decimal amount string and converts it into uppercase RMB text.
 * This function rejects inputs with more than two decimal places instead of rounding.
 */
export function rmbToRmbFromString(amount: string): string
