/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let loadError = null

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (_) {
      return true
    }
  }

  const { glibcVersionRuntime } = process.report.getReport().header
  return !glibcVersionRuntime
}

function loadBinding(localName, packageName) {
  try {
    const localPath = join(__dirname, localName)
    if (existsSync(localPath)) {
      return require(localPath)
    }

    return require(packageName)
  } catch (error) {
    loadError = error
    return null
  }
}

function loadDarwinBinding() {
  const universal = loadBinding('RS-rmbToRMB.darwin-universal.node', '@rs/rmb-to-rmb-darwin-universal')
  if (universal) {
    return universal
  }

  switch (arch) {
    case 'x64':
      return loadBinding('RS-rmbToRMB.darwin-x64.node', '@rs/rmb-to-rmb-darwin-x64')
    case 'arm64':
      return loadBinding('RS-rmbToRMB.darwin-arm64.node', '@rs/rmb-to-rmb-darwin-arm64')
    default:
      throw new Error(`Unsupported architecture on macOS: ${arch}`)
  }
}

function loadLinuxBinding() {
  const libc = isMusl() ? 'musl' : 'gnu'

  switch (arch) {
    case 'x64':
      return loadBinding(`RS-rmbToRMB.linux-x64-${libc}.node`, `@rs/rmb-to-rmb-linux-x64-${libc}`)
    case 'arm64':
      return loadBinding(`RS-rmbToRMB.linux-arm64-${libc}.node`, `@rs/rmb-to-rmb-linux-arm64-${libc}`)
    case 'arm':
      return loadBinding('RS-rmbToRMB.linux-arm-gnueabihf.node', '@rs/rmb-to-rmb-linux-arm-gnueabihf')
    case 'riscv64':
      return loadBinding(`RS-rmbToRMB.linux-riscv64-${libc}.node`, `@rs/rmb-to-rmb-linux-riscv64-${libc}`)
    case 's390x':
      return loadBinding('RS-rmbToRMB.linux-s390x-gnu.node', '@rs/rmb-to-rmb-linux-s390x-gnu')
    default:
      throw new Error(`Unsupported architecture on Linux: ${arch}`)
  }
}

function loadWindowsBinding() {
  switch (arch) {
    case 'x64':
      return loadBinding('RS-rmbToRMB.win32-x64-msvc.node', '@rs/rmb-to-rmb-win32-x64-msvc')
    case 'ia32':
      return loadBinding('RS-rmbToRMB.win32-ia32-msvc.node', '@rs/rmb-to-rmb-win32-ia32-msvc')
    case 'arm64':
      return loadBinding('RS-rmbToRMB.win32-arm64-msvc.node', '@rs/rmb-to-rmb-win32-arm64-msvc')
    default:
      throw new Error(`Unsupported architecture on Windows: ${arch}`)
  }
}

function loadAndroidBinding() {
  switch (arch) {
    case 'arm64':
      return loadBinding('RS-rmbToRMB.android-arm64.node', '@rs/rmb-to-rmb-android-arm64')
    case 'arm':
      return loadBinding('RS-rmbToRMB.android-arm-eabi.node', '@rs/rmb-to-rmb-android-arm-eabi')
    default:
      throw new Error(`Unsupported architecture on Android: ${arch}`)
  }
}

switch (platform) {
  case 'android':
    nativeBinding = loadAndroidBinding()
    break
  case 'darwin':
    nativeBinding = loadDarwinBinding()
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    nativeBinding = loadBinding('RS-rmbToRMB.freebsd-x64.node', '@rs/rmb-to-rmb-freebsd-x64')
    break
  case 'linux':
    nativeBinding = loadLinuxBinding()
    break
  case 'win32':
    nativeBinding = loadWindowsBinding()
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error('Failed to load native binding')
}

const { rmbToRmb, rmbToRmbFromCents, rmbToRmbFromString } = nativeBinding

module.exports.rmbToRmb = rmbToRmb
module.exports.rmbToRmbFromCents = rmbToRmbFromCents
module.exports.rmbToRmbFromString = rmbToRmbFromString
